export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';

export const REGISTER_PIN_REQUEST = 'REGISTER_PIN_REQUEST';
export const REGISTER_PIN_SUCCESS = 'REGISTER_PIN_SUCCESS';
export const REGISTER_PIN_FAILED = 'REGISTER_PIN_FAILED';

export const REG_RES_REQUEST = 'REG_RES_REQUEST';
export const REG_RES_SUCCESS = 'REG_RES_SUCCESS';
export const REG_RES_FAILED = 'REG_RES_FAILED';
